name: Push built docker image straight over the wire
on:
  push:
    branches:
      - master

jobs:
  docker_catapult:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Repo Name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Debug Repo name
        run: echo $REPO_NAME
      - name: Build Docker Image
        run: docker image build -t foxproxy .
      - name: Save Docker Image
        run: docker save foxproxy -o fp.tar
      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: hsnipe.moe
          user: root
          key: ${{secrets.SSH_KEY}}
          scp: |
            ./fp.tar => /home/
          last_ssh: |
            docker image load --input /home/fp.tar
            docker stop -t 2 fox || true
            docker run -p 40002:80 -d --name fox --rm foxproxy
